name:                genjwk
version:             0.1.0.0
github:              "prosumma/hs-genjwk"
license:             MIT 
author:              "Gregory Higley / Prosumma Inc."
maintainer:          "greg@prosumma.com"
copyright:           "2025 Prosumma Inc."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/prosumma/hs-genjwk#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- base64-bytestring
- rio

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  genjwk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genjwk

tests:
  genjwk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genjwk
